name: do the magic

on:
    schedule:
        - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - run: |
          deno --version
          deno run --allow-read=./src,./types,.env,.env.defaults --allow-net src/magic.ts