name: do the magic

on:
    schedule:
        - cron: "0 * * * *"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: denolib/setup-deno@v2
              with:
                  deno-version: v1.x
            - name: Make changes
              run: deno run --allow-read=./src,./types,.env,.env.defaults,README.template.md --allow-write --allow-net --unstable src/magic.ts
            - name: Commit files
              run: git commit -m "updating readme" -a
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
