name: do the magic

on:
    schedule:
        - cron: "0 11,17,21 * * *"
    workflow_dispatch:
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - uses: denolib/setup-deno@v2
              with:
                  deno-version: v1.x
            - name: Make changes
              env:
                  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
                  SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
                  SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  deno run --allow-read=./src,./types,.env,.env.defaults,README.template.md --allow-write --allow-env --allow-net --unstable src/magic.ts
            - uses: EndBug/add-and-commit@v4
              with:
                  add: "README.md"
                  author_name: anonymous
                  author_email: anonymous@anonymous.com
                  message: "updating readme"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
